### ISSUE TITLE
A significant amount of time in Queue() is spent grabbing the logger & ignoreing log lines

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/caduceus#194]
Under production load, we're seeing about 50% of the time spend in Queue() spent grabbing a logger and then logging to it.

The log messages are not really all that useful & could be done away with in favour of the metrics.

![profile002](https://user-images.githubusercontent.com/698825/79542359-588b2e00-8040-11ea-9502-6166420012c3.png)

**Comment by johnabass** [comment]
The above output shows that it's the `Caller` taking up most of the time, which is a known `golang` issue.  Rather than removing logging, we should stop using https://pkg.go.dev/github.com/go-kit/kit/log?tab=doc#Caller.  It provides dubious benefit, and is brittle across `golang` versions and library code since it depends on a hardcoded set of stackframes to determine the calling function.

**Comment by kristinaspring** [comment]
After discussing with John, the `Caller` is used in these logging functions from webpa-common:
https://github.com/xmidt-org/webpa-common/blob/master/logging/logger.go#L98

the best solution is to not use them in Caduceus.  Since Caduceus uses the webhook package quite a bit, I made an issue to remove them there as well:
https://github.com/xmidt-org/webpa-common/issues/468
